IMAGE_GRIDS_PATH = '/projects/standard/cse-summer25/shared/group2/data/S2_IMAGE_NUMPY'
LABEL_GRIDS_PATH = '/projects/standard/cse-summer25/shared/group2/data/S2_LABELS_NUMPY'

tile = 'T03VWJ'
date = '20190701'

image_file_suffix = "image_raw_values.npy"
label_file_suffix = "label_values.npy"

# Experiment ID and experiment settings
experiment_id = 'EXP3'

train_percent = 10
val_percent = 30
test_percent = 60

train_grids = f'experiments/{experiment_id}/train_grids.txt'
val_grids = f'experiments/{experiment_id}/val_grids.txt'
test_grids = f'experiments/{experiment_id}/test_grids.txt'
test_grids_no_rivers = f'experiments/{experiment_id}/test_grids_no_rivers.txt'

means = f'experiments/{experiment_id}/train_band_mean.npy'
stds = f'experiments/{experiment_id}/train_band_std.npy'

patch_size = (256, 256)
stride = (224, 224)

batch_size = 16

water_occurrence_threshold = 25               # for processing labels

band = 6                                      # The band that is used to plot images

# Training loop
num_epochs = 50                               # Number of training epochs
num_visual_samples = 3                        # Number of plots generated by each epoch
scheduler_on = False                           # True: ReduceLROnPlateau scheduler used // False: no scheduler used
model_dir = f"saved_models/{experiment_id}"   # Directory where trained models are saved

# Testing
test_model = 45            # Epoch number of the saved model you want to test



